config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get     'admin', to: 'admin#index'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users do
    member do
      get 'ordershow'
    end
  end
  resources :microposts do
    member do
      get 'do_map'
    end
  end
  get 'carids/allmap', to: "carids#allmap",  as: 'allmap'
  
  get 'carids/order', to: "carids#ordered",  as: 'ordered_carids'
  resources :carids do
    member do
      get 'carte'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carid.rb
class Carid < ApplicationRecord
    
     has_many :microposts

end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :carid
  validates :kind,    presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validates :lat,     presence: true
  validates :lng,     presence: true
  validates :logtime, presence: true
  validates :carid_id,  presence: true
  validates :accuracy,  presence: true, numericality:{ maximum: 500 }
  validates :area,  presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
 before_save { self.email = self.email.downcase }
 validates :name, presence: true, length: { maximum: 50 }
 VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
 validates :email, presence: true, length: {maximum: 255 },
                   format: { with: VALID_EMAIL_REGEX },
                   uniqueness: { case_sensitive: false }
 has_secure_password
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private
  def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
  end     
end

app/controllers/carids_controller.rb
class CaridsController < ApplicationController
    before_action :logged_in_user
    
    def index
        if (params[:company])
            @carids = Carid.where(company:params[:company]).order("number").page(params[:page]).per(10)
        else
            @carids = Carid.all.order("created_at DESC").page(params[:page]).per(10)
        end
    end
    
    def ordered
        @companies = Carid.all.pluck(:company).uniq.sort
    end
    
    def new
        @carid = Carid.new
    end
    
    def create
        @carid = Carid.new(carid_params)
       if (@carid.save) 
           redirect_to admin_url
       else
           render 'new'
       end
    end
    
    def edit
        @carid = Carid.find(params[:id])
    end
    
    def update
        @carid = Carid.find(params[:id])
        if (@carid.update(carid_params))
           redirect_to carids_url
        else
           render 'edit'
        end
    end
    
    def carte
        @carid = Carid.find(params[:id])
        @microposts = @carid.microposts.order("created_at DESC").page(params[:page]).per(10)
    end
    
    def allmap
        if (params[:company])
           @carids = Carid.where(company:params[:company]).pluck(:id)
           @microposts = Micropost.where(carid_id: @carids)
        else
            @microposts = Micropost.all
        end
    end
    
    private
    def carid_params
        params.require(:carid).permit(:company, :number)
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
 before_action :logged_in_user, only: [:do_map]  
 
  def create
   @car = Carid.find(params[:micropost][:carid_id])
   @micropost = @car.microposts.build(micropost_params)
   if @micropost.save
     flash[:success] = "記録に成功しました" 
     redirect_to root_url(carid: @car.id)
   else
     flash[:danger] = "記録できませんでした" 
#     redirect_to root_url(carid: @carid.id)
     params[:carid] = @car.id
     render 'static_pages/home', {carid: @car.id}
   end
  end
  
  def destroy
   @micropost = current_user.microposts.find_by(id: params[:id])
   return redirect_to root_url if @micropost.nil?
   @micropost.destroy
   flash[:success] = "Micropost deleted"
   redirect_to request.referrer || root_url
  end
  
  def do_map
   @micropost = Micropost.find(params[:id])
  end
  
  private
  def micropost_params
   params.require(:micropost).permit(:content, :kind, :lat, :lng, :accuracy, :carid_id, :logtime, :area)
  end
end 
    

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.name}"
      redirect_to @user
    else
     flash[:danger] = 'invalid email/password combination'
     render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if params[:carid] != nil
      @car = Carid.find_by(id: params[:carid])
      @micropost = @car.microposts.build if @car != nil
    else
      #if logged_in?
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
   @user = User.find(params[:id])
   @carids = nil
   if (params[:company])
       @carids = Carid.where(company:params[:company]).order("created_at DESC").page(params[:page]).per(10)
   else
       @carids = Carid.all.order("created_at DESC").page(params[:page]).per(10)
   end
  end
  
  def ordershow
    @user = User.find(params[:id])
    carids_array = [];
    if (params[:company])
        carids_array = Carid.joins(:microposts).includes(:microposts).where(company:params[:company]).sort {
            |a, b| b.microposts.last.created_at <=> a.microposts.last.created_at
        }
    else
        carids_array = Carid.joins(:microposts).includes(:microposts).all.sort {
            |a, b| b.microposts.last.created_at <=> a.microposts.last.created_at
        }
    end
    @carids = Kaminari.paginate_array(carids_array).page(params[:page]).per(10)

  end
    
  def new
   @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User created"    
      redirect_to @user #これを追加    
    else
     render 'new'
    end
  end

  private

  def user_params
     params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
      !!current_user
    end

    def store_location
      session[:forwarding_url] = request.url if request.get?
    end
end    

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options= { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end  

app/views/admin/index.html.erb
<h1>管理用画面</h1>
<div class="row">
   <div class="col-sm-3">
      <%= link_to "新規CAR-ID", new_carid_path, class: "btn btn-primary" %>
   </div>
   <div class="col-sm-3">
      <%= link_to "CAR-ID一覧", carids_path, class: "btn btn-primary" %>
   </div>
   <div class="col-sm-3">
      <%= link_to "事業者順CAR-ID一覧", ordered_carids_path, class: "btn btn-primary" %>
      
   </div>
</div>

app/views/carids/_form.html.erb
<div class="row">
<div class="col-sm-6 col-sm-offset-3">
    <%= form_for(@carid) do |f| %>
        <div class="form-group">
            <%= f.label :company, class:'control-label col-sm-2' %>
            <div class="col-sm-10">
                <%= f.text_field :company, class:'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :number, class:'control-label col-sm-2' %>
            <div class="col-sm-10">
                <%= f.text_field :number, class:'form-control' %>
            </div>
        </div>
        <%= f.submit '登録', class:'btn btn-primary' %>
    <% end %>
</div>
</div>

app/views/carids/_modal.html.erb
  <!-- モーダルの配置 -->
  <div class="modal" id="modal-gmap" tabindex="-1">
      <div class="modal-dialog">
  
          <!-- モーダルのコンテンツ -->
          <div class="modal-content">
              <!-- モーダルのヘッダ -->
              <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">
                      <span aria-hidden="true">&times;</span>
                  </button>
                  <h4 class="modal-title" id="modal-label">view map (ESCキーで閉じます)</h4>
              </div>
              <!-- モーダルのボディ -->
              <div class="col-sm-12">
              <div id="modal-body">
                  <div id="gmap"></div>
                  <!-- ここにモーダル内容 -->
                  <div id="area_name"></div>
              </div>
              </div>
              <!-- モーダルのフッタ -->
              <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              </div>
          </div>
      </div>
  </div>

app/views/carids/allmap.js.erb
var pos = {};
pos.coords = {};
var gmap;
var currentPos;




var bounds = new google.maps.LatLngBounds();
<% @microposts.each_with_index do |post, idx| %>
    console.log("idx");
    console.log(<%= idx %>);
    pos.coords.latitude = <%= post.lat %>;
    pos.coords.longitude = <%= post.lng %>;
    pos.coords.accuracy = <%= post.accuracy %>;
    <% if (idx == 0) %>
        ret = get_map_render_wo_area(pos, false);
        gmap = ret[0];
        bounds.extend(currentPos);
    <% else %>
       set_maker(gmap, pos);
       currentPos = new google.maps.LatLng(pos.coords.latitude, pos.coords.longitude);
       bounds.extend(currentPos);

    <% end %>
<% end %>
gmap.fitBounds(bounds);
var zoomChangeBoundsListener = 
    google.maps.event.addListenerOnce(gmap, 'bounds_changed', function(event) {
        var ratio = this.getZoom();
        if (ratio > 16){
            this.setZoom(16);
        }
        else {
            this.setZoom(ratio - 1);
        }
});
setTimeout(function(){google.maps.event.removeListener(zoomChangeBoundsListener)}, 2000);

app/views/carids/carte.html.erb
<h1>Log for Carid <%= @carid.id %>: Number <%= @carid.number %></h1>

<% Time.zone = 'Bangkok' %>
<%# Time.zone = 'Tokyo' %>
<%= render 'modal' %>
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <td>Logtime</td> <td>Number</td> <td>種別</td> <td>content</td> <td>位置</td>
            <td>Map</td>
        </tr>
    </thead>
    <tbody>
       <% @microposts.each do |post| %>
           <tr>
              <td><%= post.logtime.in_time_zone('Bangkok').to_time.strftime("%Y-%m-%d %H:%M") %></td> 
              <td><%= @carid.number %></td> 
              <td><%= post.kind %></td> 
              <td><%= post.content.truncate(20) %></td> 
              <td><%= post.area %>付近</td> 
              <td>
                  <%= link_to "map", do_map_micropost_path(post), remote: true,
                     class:'btn btn-success btn-xs',
                     data:{toggle:"modal", target:"#modal-gmap"}  %>
              </td> 
           </tr>
       <% end %>
       <%= paginate @microposts %>
    </tbody>
</table>

app/views/carids/edit.html.erb
<h1>CAR-ID編集</h1>

<%= render 'form' %>

app/views/carids/index.html.erb
<div class="row">
    <div class="col-sm-9 col-sm-offset-3">
        <%= link_to "管理画面", admin_path, class:"btn btn-primary" %>
    </div>
</div>
<h2>CAR-ID一覧</h2>

<% if params[:company] %>
    <h4>事業者別一覧：<%= params[:company] %></h4>
<% end %>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <td>id</td>
            <td>company</td>
            <td>number</td>
            <td>delete</td>
        </tr>
    </thead>
    <tbody>
        <% @carids.each do |carid| %>
            <tr>
                <td><%= link_to "CAR-ID " + carid.id.to_s, edit_carid_path(carid.id), class:'btn btn-primary btn-xs' %></td>
                <td><%= carid.company %></td>
                <td><%= carid.number %></td>
                <td>
                    <%= link_to "削除", carid_path(carid.id), method: :delete, :confirm => 'Are you sure?',
                        class:'btn btn-danger btn-xs' %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

<%= paginate @carids %>

app/views/carids/new.html.erb
<div class="row">
    <div class="col-sm-9 col-sm-offset-3">
        <%= link_to "管理画面", admin_path, class:"btn btn-primary" %>
    </div>
</div>
<h1>新規CAR-ID登録</h1>


<%= render 'form' %>

app/views/carids/ordered.html.erb
<div class="row">
    <div class="col-sm-9 col-sm-offset-3">
        <%= link_to "管理画面", admin_path, class:"btn btn-primary" %>
    </div>
</div>

<h2>事業者一覧</h2>

<div class="row">
    <% @companies.each do |c| %>
        <div class="col-xs-3">
            <%= link_to c.truncate(8), carids_path({company: c}), class:"btn btn-primary"  %>
        </div>
    <% end %>
</div>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Mobileye", '#', id: "logo" %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", '#' %></li>
           <% if logged_in? %>
             <li><%= link_to "車両登録最新順", current_user %></li>
             <li><%= link_to "報告最新順", ordershow_user_path(current_user) %></li>
             <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                   Account <b class="caret"></b>    
                </a> 
                <ul class="dropdown-menu">
                    <li><%= link_to "MyPage", current_user %></li>
                    <li class="devider"</li>
                    <li>
                      <%= link_to "Log out", logout_path, method: "delete" %>
                    </li>
                </ul>
             </li>
            <% else %>
             <li><%= link_to "Log in", login_path %></li>
            <% end %>           
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mobileye</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script type="text/javascript"
      src="https://maps.google.com/maps/api/js?language=ja&key=AIzaSyBu3_RYKrHLe1dAoUQlQeGsDmLXMVP7SvQ"></script>

  </head>

  <body data-controller="<%= params[:controller] %>" data-action="<%= params[:action] %>">
    <%= render 'layouts/header' %>
    <div class="container">
     <% flash.each do |message_type, message| %> <!-- ここから -->
      <div class="alert alert-<%= message_type %>"><%= message %></div>
     <% end %>  <!-- ここまで追加 -->
    <%= yield %> 
   </div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user == micropost.user %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>                     
  </span>
</li>

app/views/microposts/do_map.js.erb
var pos = {};
pos.coords = {};
pos.coords.latitude = <%= @micropost.lat %>;
pos.coords.longitude = <%= @micropost.lng %>;
pos.coords.accuracy = <%= @micropost.accuracy %>;
get_map_render(pos);

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
 <div id="error_explanation">
  <div class="alert alert-danger">
    <%#= I18n.t('The form contains') %>
    <%= I18n.t('.form') %> <%= pluralize(object.errors.count, I18n.t("error")) %>
  </div>     
  <ul>
  <% object.errors.full_messages.each do |msg| %>
   <li><%= msg %></li>
  <% end %> 
  </ul>
 </div>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
    <div class="radio-inline">
      <div class="col-xs-4">
        <%= f.radio_button :kind, :速度オーバー %><%= f.label :kind, :速度オーバー, class:"control-label" %>
      </div>
      <div class="col-xs-4">
        <%= f.radio_button :kind, :急発進 %><%= f.label :kind, :急発進, class:"control-label" %>
      </div>
      <div class="col-xs-4">
        <%= f.radio_button :kind, :急ブレーキ %><%= f.label :kind, :急ブレーキ, class:"control-label" %>
      </div>
      <div class="col-xs-4">
        <%= f.radio_button :kind, :居眠り %><%= f.label :kind, :居眠り, class:"control-label" %>
      </div>
      <div class="col-xs-4">
        <%= f.radio_button :kind, :よそ見 %><%= f.label :kind, :よそ見, class:"control-label" %>
      </div>
      <div class="col-xs-4">
        <%= f.radio_button :kind, :信号無視 %><%= f.label :kind, :信号無視, class:"control-label" %>
      </div>
      <div class="col-xs-4">
        <%= f.radio_button :kind, :歩行者無視 %><%= f.label :kind, :歩行者無視, class:"control-label" %>
      </div>
      <div class="col-xs-4">
        <%= f.radio_button :kind, :あやうく事故 %><%= f.label :kind, :あやうく事故, class:"control-label" %>
      </div>
      <div class="col-xs-4">
        <%= f.radio_button :kind, :その他 %><%= f.label :kind, :その他, class:"control-label" %>
      </div>
    </div>
    <h5>コメント</h5>
  <div class="field">
    <%= f.text_area :content, placeholder: "内容を入力してください...(キー入力で消えます)" %>
  </div>
  <%= f.hidden_field :carid_id, value: @micropost.carid.id %>
  <%= f.hidden_field :lat %>
  <%= f.hidden_field :lng %>
  <%= f.hidden_field :accuracy, value: 1000 %>
  <%= f.hidden_field :logtime, value: gmtimestr %>
  <%= f.hidden_field :area, value: "" %>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

    

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/home.html.erb
<% if @car != nil %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%#= render 'shared/user_info' %>  
        <div class="provider">事業者名:<%= @micropost.carid.company %></div>
        <div class="number">車両番号:<%= @micropost.carid.number %></div>
         
        <% Time.zone = 'UTC' %>
        <% ntime = Time.now;  gmtimestr= ntime.in_time_zone('UTC').strftime("%Y/%m/%d %02H:%02M") %>
        <% Time.zone = 'Bangkok' %>
        <% ltimestr = ntime.in_time_zone('Asia/Bangkok').strftime("%Y/%m/%d %02H:%02M") %>
        <div class="rtime">時刻： <%= ltimestr %> / <%= Time.zone.name %></div>
        <% Time.zone = 'UTC' %>

      </section>        
      <section class="micropost_form">
        <%= render 'shared/micropost_form', {gmtimestr: gmtimestr} %>  
        緯度<div class="lat"></div>
        経度<div class="lng"></div>
        精度<div class="accurate"></div> 
      </section>
    </aside>  
    <div id="gmapwrap" class="col-md-8">
      <div id="gmap"></div>
      <div id="area_name"></div>
    </div>
  </div>
<% else %>
  <div class="center jumbotoron">
    <h1>Welcome to the Mobileye</h1>
    
    <%#= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
  <div class="row">
    <div id="sample" class="col-md-4">
      This is sample
    </div>
    <div id="gmapwrap" class="col-md-8">
      <div id="gmap"></div>
      <div id="area_name"></div>
    </div>
  </div>
<% end %>  
  

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
     <%= render 'shared/error_messages', object: f.object %> <!--ここを追加-->
    
     <%= f.label :name %>
     <%= f.text_field :name, class: 'form-control' %>
     
     <%= f.label :email %>
     <%= f.text_field :email, class: 'form-control' %>
     
     <%= f.label :password %>
     <%= f.password_field :password, class: 'form-control' %>
     
     <%= f.label :password_confirmation, "Confirmation" %>
     <%= f.password_field :password_confirmation, class: 'form-control' %>
     
     <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>    
</div>

app/views/users/ordershow.html.erb
<%= render 'carids/modal' %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <%= link_to "新規車両登録", new_carid_path, class:"btn btn-success" %>
      <%= link_to "管理画面",  admin_path, class:"btn btn-primary" %>
    </section>
  </aside> 
  <div class="col-md-8">
    <div class="row">
     <%= link_to "車両登録最新順", @user, class:"btn btn-default col-xs-offset-1" %>
     <span class="btn btn-primary col-xs-offset-1"> >>報告発生最新順<< </span>
     <%#= link_to ">> All map <<", allmap_path(company: params[:company]), remote: true,
                     class:'btn btn-warning col-xs-offset-1',
                     data:{toggle:"modal", target:"#modal-gmap"}  %>
    </div>
    <% if params[:company] %>
      <div class="row my-1">
        事業者指定：<span class="btn btn-warning btn-xs"><%= params[:company] %></span>
        : <%= link_to "Reset", ordershow_user_path(@user), class:"btn btn-success btn-xs" %>
      </div>
    <% end %>
    <table class="table table-striped table-bordered">
      <tr>
        <thead>
          <td>Car-ID</td> <td>Company</td> <td>Number</td>
          <td>Edit</td> <td>Carte</td>
        </thead>
      </tr>
      <tbody>
        <% @carids.each do |car| %>
          <tr>
           <td><%= car.id %></td> 
           <td><%= link_to car.company, ordershow_user_path(@user, company:car.company) %></td> 
           <td><%= car.number %></td> 
           <td class="center"><%= link_to :Edit, edit_carid_path(car.id), class:"btn btn-primary btn-xs" %></td>
           <td class="center">
             <%= link_to carte_carid_path(car.id) do %>
                <span class="btn btn-success btn-xs">Carte 
                   <span class="badge"><%= car.microposts.count %> 件</span>
                </span>
             <% end %>
           </td>
          </tr>
        
        <% end %>
 
      </tbody>
    </table>
   <%= paginate @carids %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <%= link_to "新規車両登録", new_carid_path, class:"btn btn-success" %>
      <%= link_to "管理画面",  admin_path, class:"btn btn-primary" %>
    </section>
  </aside> 
  <div class="col-md-8">
    <div class="row">
     <span class="btn btn-primary col-xs-offset-1">>>車両登録最新順<<</span>
     <%= link_to "報告発生最新順", ordershow_user_path(@user), class:"btn btn-default col-xs-offset-1" %>
    </div>
    <% if params[:company] %>
      <div class="row my-1">
        事業者指定：<span class="btn btn-warning btn-xs"><%= params[:company] %></span>
        : <%= link_to "Reset", user_path(@user), class:"btn btn-success btn-xs" %>
      </div>
    <% end %>
    <table class="table table-striped table-bordered">
      <tr>
        <thead>
          <td>Car-ID</td> <td>Company</td> <td>Number</td>
          <td>Edit</td> <td>Carte</td>
        </thead>
      </tr>
      <tbody>
        <% @carids.each do |car| %>
          <tr>
           <td><%= car.id %></td> 
           <td><%= link_to car.company, user_path(@user.id, company:car.company) %></td> 
           <td><%= car.number %></td> 
           <td class="center"><%= link_to :Edit, edit_carid_path(car.id), class:"btn btn-primary btn-xs" %></td>
           <td class="center">
             <%= link_to carte_carid_path(car.id) do %>
                <span class="btn btn-success btn-xs">Carte 
                   <span class="badge"><%= car.microposts.count %> 件</span>
                </span>
             <% end %>
           </td>
          </tr>
        
        <% end %>
 
      </tbody>
    </table>
   <%= paginate @carids %>
  </div>
</div>